// ------------------------------------------------------------------------------------------------
// <copyright file="XmiElementWriterFacade.cs" company="Starion Group S.A.">
//
//   Copyright 2026 Starion Group S.A.
//   SPDX-License-Identifier: Apache-2.0
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace Auriga.Xmi.Diagram.AutoGenXmiWriters
{
    using System;
    using System.Collections.Generic;
    using System.Xml;

    using Auriga.Core;
    using Auriga.Xmi.Core.Writers;

    using Microsoft.Extensions.Logging;

    /// <summary>
    /// The generated registry that maps an element's runtime type to the writer that serializes it, and
    /// writes a contained element by dispatching on that type. The inverse of <c>XmiReaderFacade</c>.
    /// </summary>
    public sealed class XmiElementWriterFacade : IXmiElementWriterFacade
    {
        private readonly Dictionary<Type, IXmiElementWriter> writers;

        /// <summary>
        /// Initializes a new instance of the <see cref="XmiElementWriterFacade"/> class.
        /// </summary>
        /// <param name="loggerFactory">the logger factory shared with every writer, or <c>null</c> to disable logging</param>
        public XmiElementWriterFacade(ILoggerFactory? loggerFactory = null)
        {
            this.writers = new Dictionary<Type, IXmiElementWriter>()
            {
                [typeof(Auriga.Diagram.Viewpoint.Description.Audit.TemplateInformationSection)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Audit.TemplateInformationSectionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Concern.ConcernDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Concern.ConcernDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Concern.ConcernSet)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Concern.ConcernSetWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.AdditionalLayer)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.AdditionalLayerWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.AnnotationEntry)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.AnnotationEntryWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.BackgroundConditionalStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.BackgroundConditionalStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.BackgroundStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.BackgroundStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.BasicMessageMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.BasicMessageMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.BooleanLayoutOption)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.BooleanLayoutOptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.CellEditorTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.CellEditorToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.CellUpdater)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.CellUpdaterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.ColorStep)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.ColorStepWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.ColumnMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.ColumnMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.CombinedFragmentMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.CombinedFragmentMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.CompositeLayout)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.CompositeLayoutWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.ComputedColor)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.ComputedColorWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.ConditionalContainerStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.ConditionalContainerStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.ConditionalEdgeStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.ConditionalEdgeStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.ConditionalNodeStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.ConditionalNodeStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.ContainerMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.ContainerMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.ContainerMappingImport)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.ContainerMappingImportWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.CoveredLifelinesVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.CoveredLifelinesVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.CreateCellTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.CreateCellToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.CreateColumnTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.CreateColumnToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.CreateCrossColumnTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.CreateCrossColumnToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.CreateLineTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.CreateLineToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.CreationMessageMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.CreationMessageMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.CrossTableDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.CrossTableDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.CustomLayoutConfiguration)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.CustomLayoutConfigurationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Customization)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.CustomizationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.DAnnotation)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.DAnnotationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.DAnnotationEntry)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.DAnnotationEntryWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.DecorationDescriptionsSet)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.DecorationDescriptionsSetWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.DeleteColumnTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.DeleteColumnToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.DeleteLineTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.DeleteLineToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.DestructionMessageMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.DestructionMessageMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.DiagramDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.DiagramDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.DiagramExtensionDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.DiagramExtensionDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.DiagramImportDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.DiagramImportDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.DoubleLayoutOption)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.DoubleLayoutOptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.EAttributeCustomization)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.EAttributeCustomizationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.EReferenceCustomization)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.EReferenceCustomizationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.EdgeMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.EdgeMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.EdgeMappingImport)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.EdgeMappingImportWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.EditionTableDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.EditionTableDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.ElementColumnMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.ElementColumnMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.EndOfLifeMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.EndOfLifeMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.EnumLayoutOption)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.EnumLayoutOptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.EnumLayoutValue)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.EnumLayoutValueWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.EnumSetLayoutOption)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.EnumSetLayoutOptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Environment)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.EnvironmentWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.ExecutionMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.ExecutionMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.FeatureColumnMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.FeatureColumnMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.FixedColor)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.FixedColorWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.ForegroundConditionalStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.ForegroundConditionalStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.ForegroundStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.ForegroundStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.GateMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.GateMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.GenericDecorationDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.GenericDecorationDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Group)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.GroupWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.IdentifiedElement)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.IdentifiedElementWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.InstanceRoleMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.InstanceRoleMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.IntegerLayoutOption)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.IntegerLayoutOptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.InteractionContainerMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.InteractionContainerMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.InteractionUseMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.InteractionUseMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.InterpolatedColor)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.InterpolatedColorWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.IntersectionMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.IntersectionMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.JavaExtension)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.JavaExtensionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.LabelEditTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.LabelEditToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Layer)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.LayerWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.LineMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.LineMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.MappingBasedDecoration)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.MappingBasedDecorationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.MessageEndVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.MessageEndVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.MetamodelExtensionSetting)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.MetamodelExtensionSettingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.NodeMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.NodeMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.NodeMappingImport)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.NodeMappingImportWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.ObservationPointMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.ObservationPointMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.OperandMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.OperandMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.OrderedTreeLayout)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.OrderedTreeLayoutWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.ReturnMessageMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.ReturnMessageMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.SemanticBasedDecoration)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.SemanticBasedDecorationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.SequenceDiagramDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.SequenceDiagramDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.StateMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.StateMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.StringLayoutOption)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.StringLayoutOptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.SystemColor)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.SystemColorWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.SytemColorsPalette)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.SytemColorsPaletteWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.TableCreationDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.TableCreationDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.TableMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.TableMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.TableNavigationDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.TableNavigationDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.TableTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.TableToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.Description.TableVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.Description.TableVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.TypedVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.TypedVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.UserColorsPalette)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.UserColorsPaletteWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.UserFixedColor)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.UserFixedColorWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.VSMElementCustomization)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.VSMElementCustomizationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.VSMElementCustomizationReuse)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.VSMElementCustomizationReuseWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Viewpoint)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.ViewpointWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.AbsoluteBoundsFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.AbsoluteBoundsFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.AppliedCompositeFilters)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.AppliedCompositeFiltersWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.BeginLabelStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.BeginLabelStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.BorderedStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.BorderedStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.BracketEdgeStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.BracketEdgeStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.BundledImage)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.BundledImageWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.CenterLabelStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.CenterLabelStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.CollapseFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.CollapseFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.ComputedStyleDescriptionRegistry)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.ComputedStyleDescriptionRegistryWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.CustomStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.CustomStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.DDiagram)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DDiagramWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.DEdge)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DEdgeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.DNode)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DNodeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.DNodeContainer)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DNodeContainerWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.DNodeList)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DNodeListWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.DNodeListElement)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DNodeListElementWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.DSemanticDiagram)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DSemanticDiagramWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Dot)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DotWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.DragAndDropTarget)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.DragAndDropTargetWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.EObjectVariableValue)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.EObjectVariableValueWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.EdgeStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.EdgeStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Ellipse)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.EllipseWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.EndLabelStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.EndLabelStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.FilterVariableHistory)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.FilterVariableHistoryWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.FlatContainerStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.FlatContainerStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.FoldingFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.FoldingFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.FoldingPointFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.FoldingPointFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.GaugeCompositeStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.GaugeCompositeStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.GaugeSection)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.GaugeSectionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.HideFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.HideFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.HideLabelFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.HideLabelFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.IndirectlyCollapseFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.IndirectlyCollapseFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Lozenge)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.LozengeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Note)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.NoteWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.ShapeContainerStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.ShapeContainerStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Square)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.SquareWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.TypedVariableValue)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.TypedVariableValueWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.WorkspaceImage)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.WorkspaceImageWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Filter.CompositeFilterDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Filter.CompositeFilterDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Filter.MappingFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Filter.MappingFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Filter.VariableFilter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Filter.VariableFilterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.ArrowStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ArrowStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.BasicCompartment)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.BasicCompartmentWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.BasicDecorationNode)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.BasicDecorationNodeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.BasicSemanticCompartment)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.BasicSemanticCompartmentWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.BooleanListValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.BooleanListValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.BooleanValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.BooleanValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Bounds)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.BoundsWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.ByteArrayValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ByteArrayValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.CanonicalStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.CanonicalStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Compartment)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.CompartmentWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Connector)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ConnectorWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.ConnectorStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ConnectorStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.DataTypeStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DataTypeStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.DecorationNode)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DecorationNodeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.DescriptionStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DescriptionStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Diagram)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DiagramWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.DiagramLinkStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DiagramLinkStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.DiagramStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DiagramStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.DoubleListValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DoubleListValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.DoubleValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DoubleValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.DrawerStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.DrawerStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.EObjectListValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.EObjectListValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.EObjectValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.EObjectValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Edge)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.EdgeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.FillStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.FillStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.FilteringStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.FilteringStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.FontStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.FontStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Guide)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.GuideWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.GuideStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.GuideStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.HintedDiagramLinkStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.HintedDiagramLinkStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.IdentityAnchor)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.IdentityAnchorWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Image)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ImageWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.ImageBufferStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ImageBufferStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.ImageStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ImageStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.IntListValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.IntListValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.IntValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.IntValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.LineStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.LineStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.LineTypeStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.LineTypeStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.ListCompartment)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ListCompartmentWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.ListValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ListValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Location)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.LocationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.MultiDiagramLinkStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.MultiDiagramLinkStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.NamedStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.NamedStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Node)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.NodeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.NodeEntry)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.NodeEntryWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.PageStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.PageStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.PropertiesSetStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.PropertiesSetStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.PropertyValue)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.PropertyValueWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Ratio)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.RatioWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.RelativeBendpoints)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.RelativeBendpointsWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.RoundedCornersStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.RoundedCornersStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.RoutingStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.RoutingStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.SemanticListCompartment)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.SemanticListCompartmentWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Shape)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ShapeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.ShapeStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.ShapeStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.SingleValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.SingleValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.Size)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.SizeWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.SortingStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.SortingStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.StandardDiagram)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.StandardDiagramWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.StringListValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.StringListValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.StringToPropertyValueMapEntry)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.StringToPropertyValueMapEntryWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.StringValueStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.StringValueStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.TextStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.TextStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Notation.TitleStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Notation.TitleStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Ordering.CompoundEventEnd)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Ordering.CompoundEventEndWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Ordering.EventEndsOrdering)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Ordering.EventEndsOrderingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Ordering.InstanceRolesOrdering)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Ordering.InstanceRolesOrderingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Ordering.SingleEventEnd)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Ordering.SingleEventEndWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.SequenceDDiagram)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.SequenceDDiagramWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Style.BasicLabelStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Style.BasicLabelStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.BeginLabelStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.BeginLabelStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.BorderedStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.BorderedStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.BracketEdgeStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.BracketEdgeStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.BundledImageDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.BundledImageDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.CenterLabelStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.CenterLabelStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.CustomStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.CustomStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.DotDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.DotDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.EdgeStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.EdgeStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.EllipseNodeDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.EllipseNodeDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.EndLabelStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.EndLabelStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.FlatContainerStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.FlatContainerStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.GaugeCompositeStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.GaugeCompositeStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.GaugeSectionDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.GaugeSectionDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Style.LabelBorderStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Style.LabelBorderStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Style.LabelBorderStyles)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Style.LabelBorderStylesWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Style.LabelStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Style.LabelStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.LozengeNodeDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.LozengeNodeDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.NoteDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.NoteDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.ShapeContainerStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.ShapeContainerStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.SquareDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.SquareDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Style.TooltipStyleDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Style.TooltipStyleDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Style.WorkspaceImageDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Style.WorkspaceImageDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.DCell)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.DCellWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.DCellStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.DCellStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.DFeatureColumn)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.DFeatureColumnWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.DLine)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.DLineWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.DTable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.DTableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.DTableElementStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.DTableElementStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Table.DTargetColumn)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Table.DTargetColumnWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TAbstractMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TAbstractMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TBasicMessageMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TBasicMessageMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TConditionalExecutionStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TConditionalExecutionStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TConditionalLifelineStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TConditionalLifelineStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TConditionalMessageStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TConditionalMessageStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TCreationMessageMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TCreationMessageMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TDestructionMessageMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TDestructionMessageMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TExecutionMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TExecutionMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TExecutionStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TExecutionStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TLifelineMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TLifelineMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TLifelineStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TLifelineStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TMessageStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TMessageStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TReturnMessageMapping)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TReturnMessageMappingWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TSequenceDiagram)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TSequenceDiagramWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Template.TTransformer)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Template.TTransformerWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.AcceleoVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.AcceleoVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.BehaviorTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.BehaviorToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.Case)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.CaseWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ChangeContext)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ChangeContextWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.CombinedFragmentCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.CombinedFragmentCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.ContainerCreationDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.ContainerCreationDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.ContainerDropDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.ContainerDropDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ContainerViewVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ContainerViewVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.CreateEdgeView)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.CreateEdgeViewWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.CreateInstance)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.CreateInstanceWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.CreateView)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.CreateViewWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.Default)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.DefaultWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.DeleteElementDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.DeleteElementDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.DeleteHook)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.DeleteHookWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.DeleteHookParameter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.DeleteHookParameterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.DeleteView)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.DeleteViewWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.DiagramCreationDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.DiagramCreationDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.DiagramNavigationDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.DiagramNavigationDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.DirectEditLabel)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.DirectEditLabelWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.DoubleClickDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.DoubleClickDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.DropContainerVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.DropContainerVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.EdgeCreationDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.EdgeCreationDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.EditMaskVariables)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.EditMaskVariablesWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ElementDeleteVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ElementDeleteVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.ElementDoubleClickVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.ElementDoubleClickVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ElementDropVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ElementDropVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ElementSelectVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ElementSelectVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ElementVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ElementVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ElementViewVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ElementViewVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.ExecutionCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.ExecutionCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ExternalJavaAction)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ExternalJavaActionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ExternalJavaActionCall)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ExternalJavaActionCallWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ExternalJavaActionParameter)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ExternalJavaActionParameterWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.FeatureChangeListener)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.FeatureChangeListenerWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.For)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ForWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.GateCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.GateCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.GroupMenu)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.GroupMenuWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.If)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.IfWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.InitEdgeCreationOperation)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.InitEdgeCreationOperationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.InitialContainerDropOperation)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.InitialContainerDropOperationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.InitialNodeCreationOperation)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.InitialNodeCreationOperationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.InitialOperation)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.InitialOperationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.InstanceRoleCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.InstanceRoleCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.InstanceRoleReorderTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.InstanceRoleReorderToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.InteractionUseCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.InteractionUseCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.Let)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.LetWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.LifelineCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.LifelineCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.MenuItemDescriptionReference)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.MenuItemDescriptionReferenceWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.MessageCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.MessageCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.MoveElement)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.MoveElementWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.NameVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.NameVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.Navigation)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.NavigationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.NodeCreationDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.NodeCreationDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.NodeCreationVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.NodeCreationVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.ObservationPointCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.ObservationPointCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.OperandCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.OperandCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.OperationAction)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.OperationActionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.PaneBasedSelectionWizardDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.PaneBasedSelectionWizardDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.PasteDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.PasteDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.PopupMenu)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.PopupMenuWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.ReconnectEdgeDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.ReconnectEdgeDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.RemoveElement)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.RemoveElementWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.ReorderTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.ReorderToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.RequestDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.RequestDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.SelectContainerVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.SelectContainerVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.SelectModelElementVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.SelectModelElementVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.SelectionWizardDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.SelectionWizardDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.SequenceDiagramToolDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.SequenceDiagramToolDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.SetObject)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.SetObjectWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.SetValue)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.SetValueWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.SourceEdgeCreationVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.SourceEdgeCreationVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.SourceEdgeViewCreationVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.SourceEdgeViewCreationVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Sequence.Description.Tool.StateCreationTool)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Sequence.Description.Tool.StateCreationToolWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.Switch)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.SwitchWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.TargetEdgeCreationVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.TargetEdgeCreationVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.TargetEdgeViewCreationVariable)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.TargetEdgeViewCreationVariableWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ToolDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ToolDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.ToolFilterDescription)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.ToolFilterDescriptionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.ToolGroup)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.ToolGroupWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.ToolGroupExtension)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.ToolGroupExtensionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Diagram.Description.Tool.ToolSection)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Diagram.Description.Tool.ToolSectionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Tool.Unset)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Tool.UnsetWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Validation.RuleAudit)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Validation.RuleAuditWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Validation.SemanticValidationRule)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Validation.SemanticValidationRuleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Validation.ValidationFix)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Validation.ValidationFixWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Validation.ValidationSet)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Validation.ValidationSetWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Description.Validation.ViewValidationRule)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.Description.Validation.ViewValidationRuleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.BasicLabelStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.BasicLabelStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DAnalysis)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DAnalysisWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DAnalysisCustomData)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DAnalysisCustomDataWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DAnalysisSessionEObject)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DAnalysisSessionEObjectWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DFile)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DFileWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DFolder)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DFolderWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DModel)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DModelWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DProject)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DProjectWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DRepresentationDescriptor)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DRepresentationDescriptorWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DResourceContainer)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DResourceContainerWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.DView)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DViewWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.Decoration)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.DecorationWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.LabelStyle)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.LabelStyleWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.MetaModelExtension)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.MetaModelExtensionWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.SessionManagerEObject)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.SessionManagerEObjectWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.ToolGroupInstance)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.ToolGroupInstanceWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.ToolInstance)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.ToolInstanceWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.ToolSectionInstance)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.ToolSectionInstanceWriter(this, loggerFactory),
                [typeof(Auriga.Diagram.Viewpoint.UIState)] = new Auriga.Xmi.Diagram.AutoGenXmiWriters.Viewpoint.UIStateWriter(this, loggerFactory),
            };
        }

        /// <summary>
        /// Whether a writer is registered for the supplied element's runtime type — used by a composite
        /// facade to route an element to the metamodel facade that owns its type.
        /// </summary>
        /// <param name="element">the element to test</param>
        /// <returns>true when this facade can write the element</returns>
        public bool CanWrite(IAurigaElement element)
        {
            return this.writers.ContainsKey(element.GetType());
        }

        /// <summary>
        /// Writes <paramref name="element"/> as a contained child under <paramref name="roleName"/> by
        /// dispatching to the writer registered for its runtime type.
        /// </summary>
        /// <param name="xmlWriter">the XML writer</param>
        /// <param name="element">the element to write</param>
        /// <param name="roleName">the containment feature's XML name</param>
        /// <param name="context">the write context</param>
        public void WriteElement(XmlWriter xmlWriter, IAurigaElement element, string roleName, IXmiWriteContext context)
        {
            this.ResolveWriter(element).Write(xmlWriter, element, roleName, context);
        }

        /// <summary>
        /// Resolves the per-type writer registered for <paramref name="element"/>'s runtime type.
        /// </summary>
        /// <param name="element">the element to resolve a writer for</param>
        /// <returns>the writer registered for the element's runtime type</returns>
        /// <exception cref="InvalidOperationException">no writer is registered for the element's type</exception>
        public IXmiElementWriter ResolveWriter(IAurigaElement element)
        {
            if (!this.writers.TryGetValue(element.GetType(), out var writer))
            {
                throw new InvalidOperationException($"No XMI writer is registered for the type '{element.GetType().FullName}'.");
            }

            return writer;
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
